using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.Win32;

namespace ClaudeHook;

/// <summary>
/// <c>ClaudeHook.exe --install</c>: standalone install path.
///   1. Writes claude-alert.sh next to the exe (regenerating it idempotently).
///   2. Wires all 5 Claude Code hooks into ~/.claude/settings.json if missing.
///   3. Registers an HKCU\...\Run autostart entry that runs --healthcheck.
/// </summary>
internal static class Install
{
    private const string AutostartKey = @"Software\Microsoft\Windows\CurrentVersion\Run";
    private const string AutostartValueName = "ClaudeHook";

    public static int Run() => RunInternal(showToast: false);

    /// <summary>
    /// Same as Run() but also pops a Windows toast at the end so the user sees the
    /// result without needing a terminal. Used when the user double-clicks the exe
    /// (the typical interactive entry point) or runs --install explicitly.
    /// </summary>
    public static int RunWithToast() => RunInternal(showToast: true);

    private static int RunInternal(bool showToast)
    {
        string exePath  = Environment.ProcessPath ?? throw new InvalidOperationException("ProcessPath null");
        string exeDir   = Path.GetDirectoryName(exePath)!;
        string shPath   = Path.Combine(exeDir, "claude-alert.sh");
        string shBash   = shPath.Replace('\\', '/');

        var report = new System.Text.StringBuilder();
        bool allGood = true;
        int addedHooks = 0;

        void Step(bool ok, string okMsg, string failMsg)
        {
            if (ok) report.AppendLine($"[ok] {okMsg}");
            else    { report.AppendLine($"[fail] {failMsg}"); allGood = false; }
        }

        Console.WriteLine($"ClaudeHook install");
        Console.WriteLine($"  exe : {exePath}");
        Console.WriteLine($"  sh  : {shPath}");

        try { WriteShellScript(shPath); Step(true, "claude-alert.sh written", ""); }
        catch (Exception ex) { Step(false, "", $"writing claude-alert.sh: {ex.Message}"); }

        try { addedHooks = WireHooks(shBash); Step(true, $"{Subscriptions.Length} hook subscriptions wired", ""); }
        catch (Exception ex) { Step(false, "", $"wiring hooks: {ex.Message}"); }

        try { RegisterAutostart(exePath); Step(true, "autostart registered", ""); }
        catch (Exception ex) { Step(false, "", $"autostart: {ex.Message}"); }

        Console.Write(report.ToString());
        if (allGood) Console.WriteLine("Done. Restart Claude Code to pick up the new hooks.");

        if (showToast)
        {
            string title = allGood ? "ClaudeHook installed" : "ClaudeHook install — issues";
            string body  = (allGood
                ? "Hooks wired into Claude Code · autostart enabled · ready.\n"
                : "Some steps failed — see details below.\n") + report.ToString().TrimEnd();
            string state = allGood ? "ready" : "asking";
            Program.ShowBalloonExternal(state, title, body);
        }

        return allGood ? 0 : 1;
    }

    // ---- script generation -------------------------------------------------

    private static void WriteShellScript(string path)
    {
        // Bash hands the exe $PPID (claude.exe) and forwards any extra args from
        // settings.json verbatim. Extras are used to pass matcher subtypes (e.g.
        // --notification-kind permission_prompt) so the exe can distinguish which
        // Notification subtype fired without Claude having to put it in the payload.
        string script =
            "#!/bin/bash\n" +
            "# Claude Alert hook wrapper — generated by ClaudeHook.exe --install. DO NOT EDIT.\n" +
            "\n" +
            "INPUT=$(cat)\n" +
            "EXE_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\n" +
            "EXE=\"$EXE_DIR/ClaudeHook.exe\"\n" +
            "\n" +
            "# $PPID is the bash parent (claude.exe — stable for the session). Extra args\n" +
            "# from settings.json (e.g. --notification-kind permission_prompt) pass through.\n" +
            "(\n" +
            "    printf '%s' \"$INPUT\" | \"$EXE\" --from-pid \"$PPID\" \"$@\" </dev/stdin >/dev/null 2>&1\n" +
            ") &\n" +
            "disown 2>/dev/null\n" +
            "exit 0\n";
        File.WriteAllBytes(path, System.Text.Encoding.UTF8.GetBytes(script));
    }

    // ---- settings.json hook wiring -----------------------------------------

    /// <summary>One entry we want present in settings.json.</summary>
    private sealed record HookEntry(string Event, string Matcher, string? ExtraArg, int TimeoutSec);

    /// <summary>
    /// The full set of subscriptions ClaudeHook installs. Rationale per row:
    ///   - SessionStart / UserPromptSubmit / PreToolUse → "busy" state (UserPromptSubmit
    ///     is the earliest signal we can get that the user has engaged Claude).
    ///   - Notification (3 separate matchers): different UX per subtype. auth_success
    ///     is subscribed but suppressed at runtime — easier to filter in the exe than
    ///     to gamble that Claude won't add new subtypes we'd miss.
    ///   - Stop AND StopFailure → "ready". This is the f75a006c-stuck-orange fix: Stop
    ///     ONLY fires on a successful turn end, StopFailure fires on rate limits / auth
    ///     errors / billing problems. Subscribing to only Stop = stuck busy forever.
    ///   - SessionEnd → "idle". Final clearance.
    /// </summary>
    private static readonly HookEntry[] Subscriptions =
    {
        new("SessionStart",      "*",                 null, 5),
        new("UserPromptSubmit",  "*",                 null, 5),
        new("PreToolUse",        "*",                 null, 5),
        new("PermissionRequest", "*",                 null, 5),   // fires when inline y/n dialog appears
        new("Notification",      "permission_prompt", "--notification-kind permission_prompt", 10),
        new("Notification",      "idle_prompt",       "--notification-kind idle_prompt",       10),
        new("Notification",      "auth_success",      "--notification-kind auth_success",       5),
        new("Stop",              "*",                 null, 10),
        new("StopFailure",       "*",                 null, 10),
        new("SessionEnd",        "*",                 null, 5),
    };

    private static int WireHooks(string shBash)
    {
        string settingsPath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".claude", "settings.json");

        JsonNode root;
        if (File.Exists(settingsPath))
        {
            string raw = File.ReadAllText(settingsPath);
            root = JsonNode.Parse(raw, new JsonNodeOptions { PropertyNameCaseInsensitive = false })
                   ?? new JsonObject();
        }
        else
        {
            Directory.CreateDirectory(Path.GetDirectoryName(settingsPath)!);
            root = new JsonObject();
        }

        if (root is not JsonObject obj)
            throw new InvalidOperationException("settings.json root is not an object");

        if (obj["hooks"] is not JsonObject hooks)
        {
            hooks = new JsonObject();
            obj["hooks"] = hooks;
        }

        // Sweep all our event keys and remove any existing claude-alert.sh entries
        // before we re-add. This migrates users from old subscription shapes (the
        // pre-StopFailure layout had no UserPromptSubmit and a single Notification
        // matcher=*; that would now collide with the new per-subtype entries).
        var allEventNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var sub in Subscriptions) allEventNames.Add(sub.Event);
        foreach (var evt in allEventNames)
        {
            if (hooks[evt] is not JsonArray arr) continue;
            for (int i = arr.Count - 1; i >= 0; i--)
            {
                if (arr[i] is not JsonObject group) continue;
                if (group["hooks"] is not JsonArray groupHooks) continue;
                for (int j = groupHooks.Count - 1; j >= 0; j--)
                {
                    if (groupHooks[j] is JsonObject h && IsOurHook(h, shBash))
                        groupHooks.RemoveAt(j);
                }
                // Drop the group entirely if we emptied it.
                if (groupHooks.Count == 0) arr.RemoveAt(i);
            }
            if (arr.Count == 0) hooks.Remove(evt);
        }

        // Add the new subscriptions.
        int added = 0;
        foreach (var sub in Subscriptions)
        {
            if (hooks[sub.Event] is not JsonArray arr)
            {
                arr = new JsonArray();
                hooks[sub.Event] = arr;
            }

            // Find or create the matcher group.
            JsonObject? group = null;
            foreach (var item in arr)
            {
                if (item is JsonObject g && (g["matcher"]?.GetValue<string>() ?? "") == sub.Matcher)
                {
                    group = g;
                    break;
                }
            }
            if (group == null)
            {
                group = new JsonObject { ["matcher"] = sub.Matcher, ["hooks"] = new JsonArray() };
                arr.Add(group);
            }
            if (group["hooks"] is not JsonArray groupHooks)
            {
                groupHooks = new JsonArray();
                group["hooks"] = groupHooks;
            }

            // Build the command line. Bash forwards extra args ("$@") to the exe.
            string commandLine = sub.ExtraArg == null ? shBash : $"{shBash} {sub.ExtraArg}";
            groupHooks.Add(new JsonObject
            {
                ["type"]    = "command",
                ["command"] = commandLine,
                ["timeout"] = sub.TimeoutSec,
            });
            added++;
        }

        var opts = new JsonSerializerOptions { WriteIndented = true };
        File.WriteAllText(settingsPath, root.ToJsonString(opts));
        return added;
    }

    /// <summary>True iff this hook entry was installed by us (command starts with our shBash).</summary>
    private static bool IsOurHook(JsonObject h, string shBash)
    {
        string cmd = h["command"]?.GetValue<string>() ?? "";
        return cmd.StartsWith(shBash, StringComparison.OrdinalIgnoreCase);
    }

    // ---- Windows autostart -------------------------------------------------

    private static void RegisterAutostart(string exePath)
    {
        using var key = Registry.CurrentUser.CreateSubKey(AutostartKey);
        if (key == null) throw new InvalidOperationException("Could not open HKCU\\...\\Run");
        // Quote the path in case it contains spaces. Healthcheck mode is silent unless
        // there's a problem to surface.
        key.SetValue(AutostartValueName, $"\"{exePath}\" --healthcheck", RegistryValueKind.String);
    }
}
